/* Generated By:JavaCC: Do not edit this line. BWParserConstants.java */
package org.glite.authz.pap.encoder;

public interface BWParserConstants {

  int EOF = 0;
  int PERMIT = 9;
  int DENY = 10;
  int DESCRIPTION = 11;
  int OBLIGATION = 12;
  int ACTION = 13;
  int RULE = 14;
  int RESOURCE = 15;
  int PRIVATE = 16;
  int STRING = 17;
  int ID = 18;
  int ID2 = 19;
  int HEX = 20;
  int NUMBER = 21;

  int DEFAULT = 0;
  int ONE_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"#\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"permit\"",
    "\"deny\"",
    "\"description\"",
    "\"obligation\"",
    "\"action\"",
    "\"rule\"",
    "\"resource\"",
    "\"private\"",
    "<STRING>",
    "<ID>",
    "<ID2>",
    "<HEX>",
    "<NUMBER>",
    "\"{\"",
    "\"}\"",
    "\"=\"",
  };

}
