/* Generated By:JavaCC: Do not edit this line. BWParserConstants.java */
package org.glite.authz.pap.encoder;

public interface BWParserConstants {

  int EOF = 0;
  int ALLOW = 9;
  int DENY = 10;
  int FQAN = 11;
  int DN = 12;
  int GA = 13;
  int RESOURCE = 14;
  int CERT = 15;
  int SERVICE = 16;
  int PILOT = 17;
  int NO = 18;
  int YES = 19;
  int BW = 20;
  int CLASS = 21;
  int EXCEPT = 22;
  int PRIVATE = 23;
  int STRING = 24;
  int ID = 25;
  int ID2 = 26;
  int HEX = 27;
  int NUMBER = 28;

  int DEFAULT = 0;
  int ONE_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"#\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"allow\"",
    "\"deny\"",
    "\"fqan\"",
    "\"dn\"",
    "\"ga\"",
    "\"resource_uri\"",
    "\"certificate\"",
    "\"service_class_assignment\"",
    "\"pilot\"",
    "\"no\"",
    "\"yes\"",
    "\"blacklist\"",
    "\"service_class\"",
    "\"except\"",
    "\"private\"",
    "<STRING>",
    "<ID>",
    "<ID2>",
    "<HEX>",
    "<NUMBER>",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"(\"",
    "\":\"",
    "\")\"",
  };

}
