/**
 * Copyright (c) Members of the EGEE Collaboration. 2006-2009.
 * See http://www.eu-egee.org/partners/ for details on the copyright holders.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JavaCC: Do not edit this line. BWParserConstants.java */
package org.glite.authz.pap.encoder.parser;

public interface BWParserConstants {

  int EOF = 0;
  int PERMIT = 9;
  int DENY = 10;
  int DESCRIPTION = 11;
  int OBLIGATION = 12;
  int ACTION = 13;
  int RULE = 14;
  int RESOURCE = 15;
  int PRIVATE = 16;
  int STRING = 17;
  int ID = 18;
  int ID2 = 19;
  int HEX = 20;
  int NUMBER = 21;

  int DEFAULT = 0;
  int ONE_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"#\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"permit\"",
    "\"deny\"",
    "\"description\"",
    "\"obligation\"",
    "\"action\"",
    "\"rule\"",
    "\"resource\"",
    "\"private\"",
    "<STRING>",
    "<ID>",
    "<ID2>",
    "<HEX>",
    "<NUMBER>",
    "\"{\"",
    "\"}\"",
    "\"=\"",
  };

}
