/**
 * Copyright (c) Members of the EGEE Collaboration. 2006-2009.
 * See http://www.eu-egee.org/partners/ for details on the copyright holders.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This package holds autogenerated classes which implement the policy file
 * parser.
 * <p>
 * As such most of those classes will be undocumented.
 * <p>
 * All public classes in this package are only such because they are generated
 * that way, and because they need to be available to the 
 * {@link org.glite.authz.pap.encoder.PolicyFileEncoder} class.  All these 
 * classes are subject to incompatible changes which may include addition or 
 * removal of methods, and changes in their signatures.  Classes may also be
 * removed without warning. No other package aside from the linked one should 
 * ever rely on them.
 */ 
package org.glite.authz.pap.encoder.parser;