/**
 * This package holds autogenerated classes which implement the policy file
 * parser.
 * <p>
 * As such most of those classes will be undocumented.
 * <p>
 * All public classes in this package are only such because they are generated
 * that way, and because they need to be available to the 
 * {@link org.glite.authz.pap.encoder.PolicyFileEncoder} class.  All these 
 * classes are subject to incompatible changes which may include addition or 
 * removal of methods, and changes in their signatures.  Classes may also be
 * removed without warning. No other package aside from the linked one should 
 * ever rely on them.
 */ 
package org.glite.authz.pap.encoder.parser;